#
# Copyright (c) 2016 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_HAVE_MRC) += car.o
obj-y += cpu_common.o
obj-y += lpc_common.o
obj-y += me_status.o
obj-y += microcode_intel.o
obj-y += report_platform.o
